#!/bin/bash

##############################
### All Aliases for my configs
##############################

## OVERRIDE SYSTEM COMMANDS

alias grep="rg"
alias htop="btop"
alias top="btop"
alias cat="bat -pp"
alias ls="exa --all --icons --git-ignore"
alias tree="exa --tree --icons --git-ignore"
alias lh="exa -alh --icons --git-ignore"
alias vim="nvim"

## Custom Aliases

alias myip="curl http://ipecho.net/plain; echo"
alias vimconfig="cd ~/dotfiles/.config/nvim && vim ."
alias zshconfig="vim ~/.zshrc"
alias myconfig="cd ~/dotfiles && vim ."
alias avl="aws-vault login"
alias ave="aws-vault exec"
alias avefa="aws-vault exec finetune-admin"
alias avlfa="aws-vault login finetune-admin"
alias ftap="cd ~/finetune/ftg"
alias ftsk="cd ~/finetune/skywarden && poetry shell && vim ."
alias ftlib="zellij -l $HOME/.config/zellij/layouts/ftglib.kdl"
alias gs="git switch -c"
alias gsm="git switch main"
alias gpso="git push --set-upstream origin"
alias gpp="git pull && git push"
alias gc="git commit -S --no-verify -m "

## Custom Magic
alias fman="compgen -c | fzf | xargs man" # search command manual
# Preview file content using bat 
alias fcont="fzf --preview 'bat -n --color=always {}' --bind 'ctrl-/:change-preview-window(down|hidden|)'"
# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
alias fhist="history | fzf --preview 'echo {}' --preview-window up:3:hidden:wrap --bind 'ctrl-/:toggle-preview' --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort' --color header:italic --header 'Press CTRL-Y to copy command into clipboard'" 
# Print tree structure in the preview window
alias ftree="fzf --preview 'tree -C {}'"

