#!/bin/bash

##############################
### All Aliases for my configs
##############################


alias vim="nvim"
alias myip="curl http://ipecho.net/plain; echo"
alias vimconfig="cd ~/dotfiles/.config/nvim && vim ."
alias zshconfig="vim ~/.zshrc"
alias myconfig="cd ~/dotfiles && vim ."
alias avl="aws-vault login"
alias ave="aws-vault exec"
alias avefa="aws-vault exec finetune-admin"
alias avlfa="aws-vault login finetune-admin"
alias ftap="cd ~/finetune/ftg-api && code ."
alias ftsk="cd ~/finetune/skywarden && poetry shell && vim ."
alias ftlib="zellij -l $HOME/.config/zellij/layouts/ftglib.kdl"
alias ls="exa --all --icons --git-ignore"
alias tree="exa --tree --icons --git-ignore"
alias lh="exa -alh --icons --git-ignore"
alias cat="bat -pp"
alias htop="btop"
alias top="btop"
