#!/bin/bash

export FZF_DEFAULT_OPTS="--bind 'enter:become(nvim {})' --height 50% --preview 'bat --color=always --style=numbers --line-range :20 {}'"

### ---- Completion options and styling -----------------------------------
zstyle ':completion:*' menu select # selectable menu
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]-_}={[:upper:][:lower:]_-}' 'r:|=*' 'l:|=* r:|=*'  # case insensitive completion
zstyle ':completion:*' special-dirs true # Complete . and .. special directories
zstyle ':completion:*' list-colors '' # colorize completion lists
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01' # colorize kill list

### --------
AWS_VAULT_BACKEND=pass
AWS_VAULT_PASS_CMD=pass
AWS_VAULT_PASS_PASSWORD_STORE_DIR=/home/claudio/.password-store
AWS_VAULT_PROMPT=pass
