#!/bin/bash

# export FZF_DEFAULT_OPTS="--bind 'enter:become(nvim {})' --height 50% --preview 'bat --color=always --style=numbers --line-range :20 {}'"
export FZF_DEFAULT_COMMAND='rg --files --hidden --vimgrep'

export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
# Preview file content using bat 
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'" 
# Print tree structure in the preview window
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"

# export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow --exclude .git'
export FZF_DEFAULT_COMMAND='rg --files --hidden --vimgrep'

### ---- Completion options and styling -----------------------------------
zstyle ':completion:*' menu select # selectable menu
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]-_}={[:upper:][:lower:]_-}' 'r:|=*' 'l:|=* r:|=*'  # case insensitive completion
zstyle ':completion:*' special-dirs true # Complete . and .. special directories
zstyle ':completion:*' list-colors '' # colorize completion lists
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01' # colorize kill list

### --------
AWS_VAULT_BACKEND=pass
AWS_VAULT_PASS_CMD=pass
AWS_VAULT_PASS_PASSWORD_STORE_DIR=/home/claudio/.password-store
AWS_VAULT_PROMPT=pass
