
[deno]
format = "via [$symbol]($style)"


[elixir]
format = 'via [$symbol]($style)'

[golang]
format = 'via [$symbol]($style)'

[lua]
format = 'via [$symbol]($style)'

[nodejs]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'

[zig]
format = 'via [$symbol]($style)'
